name: sequin

services:
  sequin:
    image: sequin/sequin:latest
    pull_policy: always
    ports:
      - "7376:7376"
    environment:
      - PG_HOSTNAME=postgres
      - PG_DATABASE=sequin
      - SECRET_KEY_BASE=wDPLYus0pvD6qJhKJICO4dauYPXfO/Yl782Zjtpew5qRBDp7CZvbWtQmY0eB13If
      - VAULT_KEY=2Sig69bIpuSm2kv0VQfDekET2qy8qUZGI8v3/h3ASiY=
    depends_on:
      - postgres

  postgres:
    image: postgres:13
    ports:
      - "7377:7377"
    environment:
      - POSTGRES_DB=sequin
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    command: [ "postgres", "-c", "wal_level=logical", "-p", "7377" ]
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
